version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_festival
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sena123
      - MYSQL_DATABASE=festival_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devops_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=sena123
      - DB_NAME=festival_db
    networks:
      - devops_net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    ports:
      - "80:80"
    networks:
      - devops_net
    depends_on:
      - backend

networks:
  devops_net:
    driver: bridge

volumes:
  db_data: